In [2]:
import pandas as pd

# Elinle oluşturduğun yola göre okuyoruz
df = pd.read_csv('../data/raw/Phishing_Legitimate_full.csv')

# İlk 5 satırı göster
df.head()

,id,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,...,IframeOrFrame,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,PctExtResourceUrlsRT,AbnormalExtFormActionR,ExtMetaScriptLinkRT,PctExtNullSelfRedirectHyperlinksRT,CLASS_LABEL
0,1,3,1,5,72,0,0,0,0,0,...,0,0,1,1,0,1,1,-1,1,1
1,2,3,1,3,144,0,0,0,0,2,...,0,0,0,1,-1,1,1,1,1,1
2,3,3,1,2,58,0,0,0,0,0,...,0,0,0,1,0,-1,1,-1,0,1
3,4,3,1,6,79,1,0,0,0,0,...,0,0,0,1,-1,1,1,1,-1,1
4,5,3,0,4,46,0,0,0,0,0,...,1,0,0,1,1,-1,0,-1,-1,1

In [3]:
# Veri seti hakkında genel bilgi (Hangi sütun sayı, hangisi boş gibi)
df.info()

# Sayısal değerlerin özeti (Ortalama, min, max değerler)
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 50 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   id                                  10000 non-null  int64
 1   NumDots                             10000 non-null  int64
 2   SubdomainLevel                      10000 non-null  int64
 3   PathLevel                           10000 non-null  int64
 4   UrlLength                           10000 non-null  int64
 5   NumDash                             10000 non-null  int64
 6   NumDashInHostname                   10000 non-null  int64
 7   AtSymbol                            10000 non-null  int64
 8   TildeSymbol                         10000 non-null  int64
 9   NumUnderscore                       10000 non-null  int64
 10  NumPercent                          10000 non-null  int64
 11  NumQueryComponents                  10000 non-null  int64
 12  NumAmpersand                        10000 non-null  int64
 13  NumHash                             10000 non-null  int64
 14  NumNumericChars                     10000 non-null  int64
 15  NoHttps                             10000 non-null  int64
 16  RandomString                        10000 non-null  int64
 17  IpAddress                           10000 non-null  int64
 18  DomainInSubdomains                  10000 non-null  int64
 19  DomainInPaths                       10000 non-null  int64
 20  HttpsInHostname                     10000 non-null  int64
 21  HostnameLength                      10000 non-null  int64
 22  PathLength                          10000 non-null  int64
 23  QueryLength                         10000 non-null  int64
 24  DoubleSlashInPath                   10000 non-null  int64
 25  NumSensitiveWords                   10000 non-null  int64
 26  EmbeddedBrandName                   10000 non-null  int64
 27  PctExtHyperlinks                    10000 non-null  float64
 28  PctExtResourceUrls                  10000 non-null  float64
 29  ExtFavicon                          10000 non-null  int64
 30  InsecureForms                       10000 non-null  int64
 31  RelativeFormAction                  10000 non-null  int64
 32  ExtFormAction                       10000 non-null  int64
 33  AbnormalFormAction                  10000 non-null  int64
 34  PctNullSelfRedirectHyperlinks       10000 non-null  float64
 35  FrequentDomainNameMismatch          10000 non-null  int64
 36  FakeLinkInStatusBar                 10000 non-null  int64
 37  RightClickDisabled                  10000 non-null  int64
 38  PopUpWindow                         10000 non-null  int64
 39  SubmitInfoToEmail                   10000 non-null  int64
 40  IframeOrFrame                       10000 non-null  int64
 41  MissingTitle                        10000 non-null  int64
 42  ImagesOnlyInForm                    10000 non-null  int64
 43  SubdomainLevelRT                    10000 non-null  int64
 44  UrlLengthRT                         10000 non-null  int64
 45  PctExtResourceUrlsRT                10000 non-null  int64
 46  AbnormalExtFormActionR              10000 non-null  int64
 47  ExtMetaScriptLinkRT                 10000 non-null  int64
 48  PctExtNullSelfRedirectHyperlinksRT  10000 non-null  int64
 49  CLASS_LABEL                         10000 non-null  int64
dtypes: float64(3), int64(47)
memory usage: 3.8 MB

,id,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,...,IframeOrFrame,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,PctExtResourceUrlsRT,AbnormalExtFormActionR,ExtMetaScriptLinkRT,PctExtNullSelfRedirectHyperlinksRT,CLASS_LABEL
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,...,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,2.445100,0.586800,3.300300,70.264100,1.818000,0.138900,0.000300,0.013100,0.32320,...,0.339600,0.03220,0.030400,0.956600,0.020200,0.353300,0.793200,0.173400,0.314100,0.500000
std,2886.89568,1.346836,0.751214,1.863241,33.369877,3.106258,0.545744,0.017319,0.113709,1.11466,...,0.473597,0.17654,0.171694,0.248037,0.820036,0.888908,0.521019,0.755771,0.897843,0.500025
min,1.00000,1.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,2500.75000,2.000000,0.000000,2.000000,48.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.000000,1.000000,-1.000000,-1.000000,1.000000,0.000000,-1.000000,0.000000
50%,5000.50000,2.000000,1.000000,3.000000,62.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.00000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.500000
75%,7500.25000,3.000000,1.000000,4.000000,84.000000,2.000000,0.000000,0.000000,0.000000,0.00000,...,1.000000,0.00000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,10000.00000,21.000000,14.000000,18.000000,253.000000,55.000000,9.000000,1.000000,1.000000,18.00000,...,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [4]:
# id sütununu siliyoruz
df.drop('id', axis=1, inplace=True)

print("Yeni sütun sayısı:", df.shape[1])

Yeni sütun sayısı: 49

In [5]:
# Korelasyon matrisini hesapla
corr_matrix = df.corr()

# CLASS_LABEL ile olan ilişkilere bak (mutlak değerce büyük olanlar en önemlileridir)
top_features = corr_matrix['CLASS_LABEL'].sort_values(ascending=False).head(11)
print("Phishing ile en güçlü bağlantısı olan 10 özellik:")
print(top_features)

Phishing ile en güçlü bağlantısı olan 10 özellik:
CLASS_LABEL                      1.000000
FrequentDomainNameMismatch       0.463956
PctNullSelfRedirectHyperlinks    0.342806
InsecureForms                    0.316380
NumDots                          0.294111
PctExtHyperlinks                 0.259728
NumSensitiveWords                0.255208
PathLevel                        0.229450
AbnormalExtFormActionR           0.185799
UrlLengthRT                      0.169513
HostnameLength                   0.169157
Name: CLASS_LABEL, dtype: float64

In [6]:
from sklearn.preprocessing import MinMaxScaler

# Sadece seçtiğimiz bu en güçlü 10 özelliği ve hedef etiketi alalım
selected_features = ['FrequentDomainNameMismatch', 'PctNullSelfRedirectHyperlinks', 
                     'InsecureForms', 'NumDots', 'PctExtHyperlinks', 
                     'NumSensitiveWords', 'PathLevel', 'AbnormalExtFormActionR', 
                     'UrlLengthRT', 'HostnameLength']

X = df[selected_features]
y = df['CLASS_LABEL']

# Normalizasyon işlemi
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Kontrol edelim: İlk satır artık 0-1 arasında mı?
print("Normalize edilmiş ilk satır:\n", X_scaled[0])

Normalize edilmiş ilk satır:
 [0.         0.         1.         0.1        0.         0.
 0.27777778 1.         0.5        0.12781955]

In [7]:
from sklearn.model_selection import train_test_split

# %80 Eğitim, %20 Test olarak bölüyoruz
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print(f"Eğitim seti boyutu: {X_train.shape}")
print(f"Test seti boyutu: {X_test.shape}")

Eğitim seti boyutu: (8000, 10)
Test seti boyutu: (2000, 10)